### ISSUE TITLE
Please add an example on how to join (append) multiple videos.

### ISSUE THREAD

**Issue by jarrodhroberson** [modfy/go-fluent-ffmpeg#10]
Can someone please add a working example on appending multiple videos together.

I can not see how to accomplish this from reading the API and it is different enough than the JavaScript fluent-ffmpeg API to not be any help. 

Is this even possible with this library binding?

**Comment by CryogenicPlanet** [comment]
cc @zackradisic can you help @jarrodhroberson out with this

**Comment by zackradisic** [comment]
Haven't added anything in the API for video concatenation but it is possible right now by manually putting ffmpeg args (see [here](https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg) for various ways to do concatenation). Here are some examples:

With ffmpeg's concat filter:
```go
err := fluentffmpeg.NewCommand("").
	InputOptions("-i", "1.mp4", "-i", "2.mp4").
	OutputOptions("-filter_complex", "[0:0] [0:1] [1:0] [1:1] concat=n=2:v=1:a=1 [v] [a]", "-map", "[v]", "-map", "[a]").
	OutputPath("./out.mp4").
	Overwrite(true).
	Run()
```

With the concat demuxer:
```bash
# concat.txt
file '/Users/zackradisic/Code/modfy/test-media/loom-hevc.mp4'
file '/Users/zackradisic/Code/modfy/test-media/loom-hevc.mp4'
```
```go


// main.go
func main() {
	err := fluentffmpeg.NewCommand("").
		InputOptions("-f", "concat", "-safe", "0", "-i", "concat.txt").
		OutputPath("./out.mp4").
		OutputLogs(outputBuf).
		Overwrite(true).
		Run()
}
```

The second option is the easiest but requires you to write the concat file to the filesystem. Writing the ffmpeg filter by hand is a little cumbersome, we can add some functionality to do it for you. Maybe something similar to the node API

```go
err := fluentffmpeg.NewCommand("").
	Input("1.mp4").
	Input("2.mp4").
	OutputPath("./out.mp4").
	MergeToFile().
	Run()
```
