### ISSUE TITLE
RunWithContext is not available

### ISSUE THREAD

**Issue by fouadkada** [modfy/go-fluent-ffmpeg#5]
after getting the module using `go get -u github.com/modfy/fluent-ffmpeg` the RunWithContext method is not available

**Comment by zackradisic** [comment]
@fouadkada, I actually forgot to tag the latest version 😅, `go get -u github.com/modfy/fluent-ffmpeg` should download v0.1.0 now. `RunWithContext` and `BuildWithContext` should be available now 👍
