### ISSUE TITLE
InputOptions help

### ISSUE THREAD

**Issue by BrennaEpp** [modfy/go-fluent-ffmpeg#7]
Hi, I'm not sure whether this is not working or if I am doing it wrong. I want to pass in options so I can trim the video.

Here is the code:
```
	buf := &bytes.Buffer{}
	err := fluentffmpeg.NewCommand("./ffmpeg-binaries/ffmpeg").
		InputOptions("-ss 00:00:10").
		InputPath("./video.mp4").
		OutputFormat("mp4").
		OutputPath("./trim.mp4").
		Overwrite(true).
		OutputLogs(buf).
		Run()

	if err != nil {
		log.Fatal(err)
	}
```
This returns `exit status 1`.

The above does not return an error if `InputOptions` is empty, but even `InputOptions("")` returns an error. Is this working as intended?

**Comment by zackradisic** [comment]
Hi @BrennaEpp, you need to separate the input options into multiple strings or ffmpeg will interpret "-ss 00:00:10" literally as one argument.

```go
// FFmpeg returns: Unrecognized option 'ss 00:00:10'
fluentffmpeg.NewCommand("").InputOptions("-ss 00:00:10").OutputPath("./trim.mp4")

// Works
fluentffmpeg.NewCommand("").InputOptions("-ss", "00:00:10").OutputPath("./trim.mp4")
```

In the future you can also read from the buffer you supplied to `OutputLogs` to get a more descriptive error straight from ffmpeg 👍
